package com.ethanaa.headhoncho.component.zone;

public enum ZoneType {

	HAND, DECK, DISCARD, WORKER_POOL, VILLAGE, COMMANDER, FRONT_LINE_LEFT, FRONT_LINE_RIGHT, INVASION, DRAFT,
	OPP_HAND, OPP_DECK, OPP_DISCARD, OPP_WORKER_POOL, OPP_VILLAGE, OPP_FRONT_LINE_LEFT, OPP_FRONT_LINE_RIGHT;
	
}
